### ISSUE TITLE
nie dziala

### ISSUE THREAD

**Issue by StrategyMasta** [micielski/wallhavened#2]
Wyskakuje mi błąd. Pisze, że na 6969 linijce wybuchł pożar.

**Comment by StrategyMasta** [comment]
Strona zaczęła się palić

**Comment by StrategyMasta** [comment]
POMOCY MÓJ KOMPUTER ZACZĄŁ DYMIĆ

**Comment by micielski** [comment]
> POMOCY MÓJ KOMPUTER ZACZĄŁ DYMIĆ  

czyli działa, zamykam
